export const STRINGS = {
  form_button_cancel_label: 'Cancelar',
  form_button_save_label: 'Salvar',
  modal_create_document_input_description_label: 'Descrição do documento',
  modal_create_document_input_description_placeholder: 'Digite a descrição do documento',
  modal_create_document_input_file_label: 'Arquivo',
  modal_create_document_input_file_placeholder: 'Escolha o arquivo',
  modal_create_document_input_link_label: 'Link do documento',
  modal_create_document_input_link_placeholder: 'Digite o link do documento',
  modal_create_document_input_title_label: 'Nome do documento',
  modal_create_document_input_title_placeholder: 'Digite o nome do documento',
  modal_create_document_title: 'Criar documento',
  table_body_button_remove: 'Remover',
  table_body_no_results: 'Nenhum documento encontrado',
  table_header_description: 'Descrição',
  table_header_title: 'Título',
  table_header_url: 'Link',
  title: 'Documentos',
}
