export const STRINGS = {
  button_cancel_label: 'Cancelar',
  form_button_label: 'Salvar',
  form_input_board_date_label: 'Data de saída',
  form_input_cancelation_rules_label: 'Regras de cancelamento',
  form_input_details_label: 'Detalhe da vaga',
  form_input_first_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 1a data limite',
  form_input_first_subscription_deadline_label: '⁠1a Data limite de inscrições',
  form_input_first_subscription_installments_label: '⁠Parcelas na 1a data limite',
  form_input_first_subscription_installments_placeholder: 'Escolha as parcelas na 1a data limite',
  form_input_first_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 1a data limite',
  form_input_first_subscription_percentage_discount_placeholder: 'Digite o percentual de desconto no PIX na 1a data limite',
  form_input_first_subscription_value_label: '⁠Valor na 1a data limite',
  form_input_first_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  form_input_group_name_label: 'Nome do grupo',
  form_input_group_name_placeholder: 'Digite o nome do grupo',
  form_input_itinerary_name_label: 'Nome do roteiro',
  form_input_itinerary_name_placeholder: 'Digite o nome do roteiro',
  form_input_landing_date_label: 'Data de volta',
  form_input_seats_label: 'Quantidade de vagas',
  form_input_seats_placeholder: 'Digite a quantidade de vagas',
  form_input_second_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_deadline_label: '⁠2a Data limite de inscrições',
  form_input_second_subscription_installments_label: '⁠Parcelas na 2a data limite',
  form_input_second_subscription_installments_placeholder: 'Escolha as parcelas na 2a data limite',
  form_input_second_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 2a data limite',
  form_input_second_subscription_percentage_discount_placeholder: 'Digite o valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_value_label: '⁠Valor na 2a data limite',
  form_input_second_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  form_input_services_label: 'Serviços inclusos',
  form_input_summary_label: 'Resumo da vaga',
  form_input_terms_and_conditions_label: 'Termos e condições',
  modal_create_document_input_description_label: 'Descrição do documento',
  modal_create_document_input_description_placeholder: 'Digite a descrição do documento',
  modal_create_document_input_file_label: 'Arquivo',
  modal_create_document_input_file_placeholder: 'Escolha o arquivo',
  modal_create_document_input_link_label: 'Link do documento',
  modal_create_document_input_link_placeholder: 'Digite o link do documento',
  modal_create_document_input_title_label: 'Nome do documento',
  modal_create_document_input_title_placeholder: 'Digite o nome do documento',
  modal_create_document_title: 'Criar documento',
  modal_create_entry_input_description_label: 'Descrição do itinário',
  modal_create_entry_input_title_label: 'Nome do itinário',
  modal_create_entry_input_title_placeholder: 'Digite o nome do itinário',
  modal_create_entry_title: 'Criar itinerário',
  section_documents_data_title: 'Documentos',
  section_entries_data_title: 'Itinerários',
  section_financial_data_title: 'Dados financeiros',
  section_geral_data_title: 'Dados gerais',
  table_documents_body_button_remove: 'Remover',
  table_documents_body_no_results: 'Nenhum documento encontrado',
  table_documents_header_description: 'Descrição',
  table_documents_header_title: 'Título',
  table_documents_header_url: 'Link',
  table_entries_body_button_remove: 'Remover',
  table_entries_header_description: 'Descrição',
  table_entries_header_title: 'Título',
  title: 'Editar roteiro',
  updated_error: 'Ocorreu um erro. Tente novamente',
  updated_success: 'Roteiro atualizado com sucesso',
}

//
