export const STRINGS = {
  button_cancel_label: 'Cancelar',
  form_button_label: 'Salvar',
  form_input_board_date_label: 'Data de saída',
  form_input_cancelation_rules_label: 'Regras de cancelamento',
  form_input_details_label: 'Detalhe da vaga',
  form_input_details_placeholder: 'Digite o detalhe da vaga',
  form_input_first_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 1a data limite',
  form_input_first_subscription_deadline_label: '⁠1a Data limite de inscrições',
  form_input_first_subscription_installments_label: '⁠Parcelas na 1a data limite',
  form_input_first_subscription_installments_placeholder: 'Escolha as parcelas na 1a data limite',
  form_input_first_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 1a data limite',
  form_input_first_subscription_percentage_discount_placeholder: 'Digite o percentual de desconto no PIX na 1a data limite',
  form_input_first_subscription_value_label: '⁠Valor na 1a data limite',
  form_input_first_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  form_input_group_name_label: 'Nome do grupo',
  form_input_group_name_placeholder: 'Digite o nome do grupo',
  form_input_itinerary_name_label: 'Nome do roteiro',
  form_input_itinerary_name_placeholder: 'Digite o nome do roteiro',
  form_input_landing_date_label: 'Data de volta',
  form_input_seats_label: 'Quantidade de vagas',
  form_input_seats_placeholder: 'Digite a quantidade de vagas',
  form_input_second_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_deadline_label: '⁠2a Data limite de inscrições',
  form_input_second_subscription_installments_label: '⁠Parcelas na 2a data limite',
  form_input_second_subscription_installments_placeholder: 'Escolha as parcelas na 2a data limite',
  form_input_second_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 2a data limite',
  form_input_second_subscription_percentage_discount_placeholder: 'Digite o valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_value_label: '⁠Valor na 2a data limite',
  form_input_second_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  form_input_services_label: 'Serviços inclusos',
  form_input_summary_label: 'Resumo da vaga',
  form_input_terms_and_conditions_label: 'Termos e condições',
  section_financial_data_title: 'Dados financeiros',
  section_geral_data_title: 'Dados gerais',
  title: 'Criar roteiro',
  updated_error: 'Ocorreu um erro. Tente novamente',
  updated_success: 'Roteiro criado com sucesso',
}

//
