export const STRINGS = {
  form_button_cancel_label: 'Cancelar',
  form_button_save_label: 'Salvar',
  form_input_first_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 1a data limite',
  form_input_first_subscription_deadline_label: '⁠1a Data limite de inscrições',
  form_input_first_subscription_installments_label: '⁠Parcelas na 1a data limite',
  form_input_first_subscription_installments_placeholder: 'Escolha as parcelas na 1a data limite',
  form_input_first_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 1a data limite',
  form_input_first_subscription_percentage_discount_placeholder: 'Digite o percentual de desconto no PIX na 1a data limite',
  form_input_first_subscription_value_label: '⁠Valor na 1a data limite',
  form_input_first_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  form_input_seats_placeholder: 'Digite a quantidade de vagas',
  form_input_second_subscription_amount_with_discount_label: '⁠Valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_deadline_label: '⁠2a Data limite de inscrições',
  form_input_second_subscription_installments_label: '⁠Parcelas na 2a data limite',
  form_input_second_subscription_installments_placeholder: 'Escolha as parcelas na 2a data limite',
  form_input_second_subscription_percentage_discount_label: 'Percentual(%) de desconto PIX na 2a data limite',
  form_input_second_subscription_percentage_discount_placeholder: 'Digite o valor com desconto no PIX na 2a data limite',
  form_input_second_subscription_value_label: '⁠Valor na 2a data limite',
  form_input_second_subscription_value_placeholder: 'Digite o valor na 1a data limite',
  title: 'Dados financeiros',
}
